### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by craftwar** [x1angli/convert2utf#5]
Python 3.5.4, win32

Python>pip install convert2utf
Collecting convert2utf
  Using cached convert2utf-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "\AppData\Local\Temp\pip-build-lhz8yq_d\convert2utf\setup.py", line 12, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "python\python35-32\lib\site-packages\pypandoc\__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

**Comment by x1angli** [comment]
This issue has been fixed in version 1.0.2
